node {
    withMaven(maven:'maven') {
        stage('Checkout') {
            git url: 'https://github.com/Cognizant-Ups/sample-spring-microservices.git', credentialsId: 'github', branch: 'master'
        }
        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('gateway-service') {
                def app = docker.build "10.154.198.38:5000/gateway-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("10.154.198.38:5000/gateway-service:${env.version}").run('-p 8764:8765 -h gateway --name gateway --link discovery --link account --link customer')
        }
    }
}
