node {
    withMaven(maven:'maven') {
        stage('Checkout') {
            git url: 'https://github.com/Cognizant-Ups/sample-spring-microservices.git', credentialsId: 'github', branch: 'master'
        }

        stage('Build') {
            sh 'mvn clean install'

            def pom = readMavenPom file:'pom.xml'
            print pom.version
            env.version = pom.version
        }

        stage('Image') {
            dir ('account-service') {
                def app = docker.build "192.168.0.104/account-service:${env.version}"
                app.push()
            }
        }

        stage ('Run') {
            docker.image("192.168.0.104/account-service:${env.version}").run('-p 2222:2222 -h account --name account')
        }    
    }
}
